

{'date': 'Sat Aug 20 2022 10:30:40.325 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 185
    main = Main().main()
  module <module> line 139
    self.marquee.main()
TypeError: 'Main' object is not callable
'''},
{'date': 'Sat Aug 20 2022 10:42:35.723 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
Exception: function statement requires a name
  module '$exec_320' line 186
main = Main().main()
'''},
