
{'date': 'Wed Dec 11 2019 11:01:34.237 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 95
  def entra_na_cesta(self, personagem)
                                       ^
SyntaxError: invalid syntax
'''},
{'date': 'Wed Dec 11 2019 11:02:04.103 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 95
  def entra_na_cesta(self, personagem)
                                       ^
SyntaxError: invalid syntax
'''},
{'date': 'Wed Dec 11 2019 11:06:54.506 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 99
  for personagem_tmp in personagens
                                    ^
SyntaxError: invalid syntax
'''},
{'date': 'Wed Dec 11 2019 11:07:09.684 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 99
  for p in personagens
                       ^
SyntaxError: invalid syntax
'''},
{'date': 'Wed Dec 11 2019 11:07:38.463 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 126
    Basico()
  module <module> line 118
    self.doggie = Personagem(DOG, destino=self.cesta_esquerda, cena=cena, tit = "10kg", x=540, y=150, w=80,h=50)
  module <module> line 36
    self.vai = destino.enta_na_cesta(self)
AttributeError: 'Cesta' object has no attribute 'enta_na_cesta'
'''},
{'date': 'Wed Dec 11 2019 11:08:05.572 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 126
    Basico()
  module <module> line 118
    self.doggie = Personagem(DOG, destino=self.cesta_esquerda, cena=cena, tit = "10kg", x=540, y=150, w=80,h=50)
  module <module> line 36
    self.vai = self.destino.enta_na_cesta(self)
AttributeError: 'Cesta' object has no attribute 'enta_na_cesta'
'''},
{'date': 'Wed Dec 11 2019 11:08:53.850 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 126
    Basico()
  module <module> line 118
    self.doggie = Personagem(DOG, destino=self.cesta_esquerda, cena=cena, tit = "10kg", x=540, y=150, w=80,h=50)
  module <module> line 36
    self.vai = self.destino.entra_na_cesta(self)
  module <module> line 99
    for p in personagens:
NameError: name 'personagens' is not defined
'''},
{'date': 'Wed Dec 11 2019 11:09:20.302 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 126
    Basico()
  module <module> line 118
    self.doggie = Personagem(DOG, destino=self.cesta_esquerda, cena=cena, tit = "10kg", x=540, y=150, w=80,h=50)
  module <module> line 36
    self.vai = self.destino.entra_na_cesta(self)
  module <module> line 99
    for p in integrantes:
NameError: name 'integrantes' is not defined
'''},
{'date': 'Wed Dec 11 2019 11:09:47.338 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 126
    Basico()
  module <module> line 118
    self.doggie = Personagem(DOG, destino=self.cesta_esquerda, cena=cena, tit = "10kg", x=540, y=150, w=80,h=50)
  module <module> line 36
    self.vai = self.destino.entra_na_cesta(self)
  module <module> line 99
    for p in integrantes:
NameError: name 'integrantes' is not defined
'''},
{'date': 'Wed Dec 11 2019 11:56:43.701 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 129
    Basico()
  module <module> line 121
    self.doggie = Personagem(DOG, destino=self.cesta_esquerda, cena=cena, tit = "10kg", x=540, y=145, w=80,h=50)
  module <module> line 36
    self.vai = self.destino.entra_na_cesta(self)
AttributeError: 'Plataforma' object has no attribute 'entra_na_cesta'
'''},
{'date': 'Wed Dec 11 2019 12:32:12.465 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 102
    Basico()
  module <module> line 94
    self.doggie = Personagem(DOG, destino=self.cesta_esquerda, cena=cena, tit = "10kg", x=540, y=145, w=80,h=50)
  module <module> line 36
    self.vai = self.destino.entra_na_cesta(self, evento=None)#self.move
TypeError: entra_na_cesta() got an unexpected keyword argument 'evento'
'''},
{'date': 'Wed Dec 11 2019 12:32:38.583 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 102
    Basico()
  module <module> line 94
    self.doggie = Personagem(DOG, destino=self.cesta_esquerda, cena=cena, tit = "10kg", x=540, y=145, w=80,h=50)
  module <module> line 36
    self.vai = self.destino.entra_na_cesta(self, evento=None)#self.move
TypeError: entra_na_cesta() got multiple values for argument 'evento'
'''},
{'date': 'Wed Dec 11 2019 12:33:12.99 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 36
  self.vai = self.destino.entra_na_cesta(evento=None,self)#self.move
                                                         ^
SyntaxError: non-keyword arg after keyword arg
'''},
{'date': 'Wed Dec 11 2019 12:41:34.227 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 104
    Controlador()
  module <module> line 96
    self.doggie = Personagem(DOG, controlador=self, cena=cena, tit = "10kg", x=540, y=145, w=80,h=50)
TypeError: __init__() got an unexpected keyword argument 'controlador'
'''},
{'date': 'Wed Dec 11 2019 12:43:06.534 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 103
    Controlador()
  module <module> line 89
    self.cesta_esquerda = Cesta(CEST, destino=self.base_topo, cena=self.base)
TypeError: __init__() got an unexpected keyword argument 'destino'
'''},
{'date': 'Wed Dec 11 2019 12:44:06.391 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 103
    Controlador()
  module <module> line 89
    self.cesta_esquerda = Cesta(CEST, destino=self.base_topo, cena=self.base)
TypeError: __init__() got an unexpected keyword argument 'destino'
'''},
{'date': 'Wed Dec 11 2019 12:53:21.138 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 80
  def inverte_topo_base_controlador:
                                    ^
SyntaxError: invalid syntax
'''},
{'date': 'Wed Dec 11 2019 14:21:26.448 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 118
    Controlador()
  module <module> line 104
    self.cesta_esquerda = Cesta(CEST, controlador=self, destino=self.base_topo, cena=self.base, x = 1)
  module <module> line 57
    self.fundo.vai = self.controlador.cesta_topo.mover
AttributeError: 'Controlador' object has no attribute 'cesta_topo'
'''},