
{'date': 'Thu Mar 28 2019 15:06:05.454 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 3
    doc['pydiv'].html=''
NameError: name 'doc' is not defined
'''},
{'date': 'Thu Mar 28 2019 16:18:42.568 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 12
    tr = shapes.triangle(length=5)
NameError: name 'shapes' is not defined
'''},
{'date': 'Wed Oct 02 2019 18:46:47.806 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 12
    tr = shapes.triangle(length=5)
NameError: name 'shapes' is not defined
'''},
{'date': 'Wed Oct 02 2019 18:47:05.245 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 12
    tr = shapes.triangle(length=5)
NameError: name 'shapes' is not defined
'''},
{'date': 'Mon Apr 25 2022 14:59:22.168 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 2
    from _spy.vitollino.jogos import Cubos, CENAS
  module _spy.vitollino.jogos line 31
    STYLE.update(width=850, height="650px")
AttributeError: 'module' object has no attribute 'update'
'''},
{'date': 'Mon Apr 25 2022 15:03:16.507 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 2
    from _spy.vitollino.jogos import Cubos, CENAS
ImportError: cannot import name 'Cubos'
'''},
{'date': 'Mon Apr 25 2022 15:03:47.518 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 2
    from _spy.vitollino.jogos import CENAS
ImportError: cannot import name 'CENAS'
'''},
{'date': 'Mon Apr 25 2022 15:04:23.713 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 2
    from _spy.vitollino import jogos
ImportError: cannot import name 'jogos'

AttributeError
Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 268
    action()
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 2
    from _spy.vitollino import jogos
'''},
{'date': 'Mon Apr 25 2022 15:11:02.319 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''<class 'Cubos'>
Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 4
    Cubos(jogos.CENAS)
NameError: name 'Cubos' is not defined
'''},
{'date': 'Mon Apr 25 2022 15:11:17.851 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''<class 'Cubos'>

Exception: bases[i].$dict is undefined
  module '$exec_1874' line 4
jogos.Cubos(jogos.CENAS)
'''},
{'date': 'Mon Apr 25 2022 15:12:50.292 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
Exception: bases[i].$dict is undefined
  module '$exec_1876' line 4
jogos.Cubos(jogos.CENAS)
'''},
{'date': 'Mon Apr 25 2022 15:13:24.951 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
Exception: bases[i].$dict is undefined
  module '$exec_1878' line 4
Cubos(CENAS)
'''},
{'date': 'Mon Apr 25 2022 15:14:26.716 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
Exception: bases[i].$dict is undefined
  module '$exec_1880' line 4
Cubos([])
'''},
{'date': 'Mon Apr 25 2022 15:19:16.138 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
Exception: bases[i].$dict is undefined
  module '$exec_320' line 4
Cubos(CENAS)
'''},
{'date': 'Wed Apr 27 2022 13:45:59.859 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 2
    @coroutine
NameError: name 'coroutine' is not defined
'''},
{'date': 'Wed Apr 27 2022 17:20:19.947 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 9
  class Roteiro
                ^
SyntaxError: invalid syntax
'''},
{'date': 'Wed Apr 27 2022 17:29:34.264 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 21
  ymara = Elemento(IMGUR.format(ELENCO[1]), y=400 cena=cena)
                                                   ^
SyntaxError: invalid syntax
'''},
{'date': 'Wed Apr 27 2022 18:12:10.786 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 32
  if __name__ == "__main__":
  ^
IndentationError: expected an indented block
'''},
{'date': 'Wed Apr 27 2022 18:12:36.4 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 41
  roteiro = Roteiro([Ator(ato,nom, 100, A.e) for ato, nom in nome_ator],
                                                                                                   ^
SyntaxError: invalid syntax
'''},
{'date': 'Wed Apr 27 2022 18:13:27.553 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 41
  roteiro = Roteiro(cena, [Ator(ato,nom, 100, A.e) for ato, nom in nome_ator],
                                                                                                         ^
SyntaxError: invalid syntax
'''},
{'date': 'Wed Apr 27 2022 18:14:11.391 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 41
  roteiro = Roteiro(cena, [Ator(ato,nom, 100, A.e) for ato, nom in nome_ator],
                                                                                                               ^
SyntaxError: invalid syntax
'''},
{'date': 'Wed Apr 27 2022 18:15:54.820 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 41
  roteiro = Roteiro(cena, [Ator(ato,nom, 100, A.e) for ato, nom in nome_ator],
                                                                                                               ^
SyntaxError: invalid syntax
'''},
{'date': 'Wed Apr 27 2022 18:17:15.720 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 42
  rot = [Fala(ato, nome, None) for for ato, nom in nome_ator]
                                    ^
SyntaxError: invalid syntax
'''},
{'date': 'Wed Apr 27 2022 18:17:25.245 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 7
    A = namedtuple('Ali','e m d')()
TypeError: __new__() missing 3 positional arguments: e,m,d
'''},
{'date': 'Wed Apr 27 2022 18:31:55.453 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 54
    roteiro = Roteiro(cena, ele, rot)
  module <module> line 18
    ator.tit = ator.nome
AttributeError: 'list' object has no attribute 'tit'
'''},
{'date': 'Wed Apr 27 2022 18:34:20.939 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 51
    roteiro = Roteiro(cena, ele, rot)
  module <module> line 18
    ator.tit = ator.nome
AttributeError: 'list' object has no attribute 'tit'
'''},
{'date': 'Wed Apr 27 2022 18:35:45.65 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 51
    roteiro = Roteiro(cena, ele, rot)
  module <module> line 19
    elenco.pop(0).vai = self.segue
AttributeError: 'list' object has no attribute 'vai'
'''},