
{'date': 'Thu Mar 28 2019 15:06:05.454 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 3
    doc['pydiv'].html=''
NameError: name 'doc' is not defined
'''},
{'date': 'Thu Mar 28 2019 16:18:42.568 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 12
    tr = shapes.triangle(length=5)
NameError: name 'shapes' is not defined
'''},
{'date': 'Wed Oct 02 2019 18:46:47.806 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 12
    tr = shapes.triangle(length=5)
NameError: name 'shapes' is not defined
'''},
{'date': 'Wed Oct 02 2019 18:47:05.245 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 12
    tr = shapes.triangle(length=5)
NameError: name 'shapes' is not defined
'''},
{'date': 'Mon Apr 25 2022 14:59:22.168 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 2
    from _spy.vitollino.jogos import Cubos, CENAS
  module _spy.vitollino.jogos line 31
    STYLE.update(width=850, height="650px")
AttributeError: 'module' object has no attribute 'update'
'''},
{'date': 'Mon Apr 25 2022 15:03:16.507 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 2
    from _spy.vitollino.jogos import Cubos, CENAS
ImportError: cannot import name 'Cubos'
'''},
{'date': 'Mon Apr 25 2022 15:03:47.518 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 2
    from _spy.vitollino.jogos import CENAS
ImportError: cannot import name 'CENAS'
'''},
{'date': 'Mon Apr 25 2022 15:04:23.713 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 2
    from _spy.vitollino import jogos
ImportError: cannot import name 'jogos'

AttributeError
Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 268
    action()
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 2
    from _spy.vitollino import jogos
'''},
{'date': 'Mon Apr 25 2022 15:11:02.319 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''<class 'Cubos'>
Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 4
    Cubos(jogos.CENAS)
NameError: name 'Cubos' is not defined
'''},
{'date': 'Mon Apr 25 2022 15:11:17.851 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''<class 'Cubos'>

Exception: bases[i].$dict is undefined
  module '$exec_1874' line 4
jogos.Cubos(jogos.CENAS)
'''},
{'date': 'Mon Apr 25 2022 15:12:50.292 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
Exception: bases[i].$dict is undefined
  module '$exec_1876' line 4
jogos.Cubos(jogos.CENAS)
'''},
{'date': 'Mon Apr 25 2022 15:13:24.951 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
Exception: bases[i].$dict is undefined
  module '$exec_1878' line 4
Cubos(CENAS)
'''},
{'date': 'Mon Apr 25 2022 15:14:26.716 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
Exception: bases[i].$dict is undefined
  module '$exec_1880' line 4
Cubos([])
'''},
{'date': 'Mon Apr 25 2022 15:19:16.138 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
Exception: bases[i].$dict is undefined
  module '$exec_320' line 4
Cubos(CENAS)
'''},
{'date': 'Wed Apr 27 2022 13:45:59.859 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 2
    @coroutine
NameError: name 'coroutine' is not defined
'''},
{'date': 'Wed Apr 27 2022 17:20:19.947 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 9
  class Roteiro
                ^
SyntaxError: invalid syntax
'''},
{'date': 'Wed Apr 27 2022 17:29:34.264 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 21
  ymara = Elemento(IMGUR.format(ELENCO[1]), y=400 cena=cena)
                                                   ^
SyntaxError: invalid syntax
'''},
{'date': 'Wed Apr 27 2022 18:12:10.786 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 32
  if __name__ == "__main__":
  ^
IndentationError: expected an indented block
'''},
{'date': 'Wed Apr 27 2022 18:12:36.4 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 41
  roteiro = Roteiro([Ator(ato,nom, 100, A.e) for ato, nom in nome_ator],
                                                                                                   ^
SyntaxError: invalid syntax
'''},
{'date': 'Wed Apr 27 2022 18:13:27.553 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 41
  roteiro = Roteiro(cena, [Ator(ato,nom, 100, A.e) for ato, nom in nome_ator],
                                                                                                         ^
SyntaxError: invalid syntax
'''},
{'date': 'Wed Apr 27 2022 18:14:11.391 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 41
  roteiro = Roteiro(cena, [Ator(ato,nom, 100, A.e) for ato, nom in nome_ator],
                                                                                                               ^
SyntaxError: invalid syntax
'''},
{'date': 'Wed Apr 27 2022 18:15:54.820 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 41
  roteiro = Roteiro(cena, [Ator(ato,nom, 100, A.e) for ato, nom in nome_ator],
                                                                                                               ^
SyntaxError: invalid syntax
'''},
{'date': 'Wed Apr 27 2022 18:17:15.720 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 42
  rot = [Fala(ato, nome, None) for for ato, nom in nome_ator]
                                    ^
SyntaxError: invalid syntax
'''},
{'date': 'Wed Apr 27 2022 18:17:25.245 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 7
    A = namedtuple('Ali','e m d')()
TypeError: __new__() missing 3 positional arguments: e,m,d
'''},
{'date': 'Wed Apr 27 2022 18:31:55.453 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 54
    roteiro = Roteiro(cena, ele, rot)
  module <module> line 18
    ator.tit = ator.nome
AttributeError: 'list' object has no attribute 'tit'
'''},
{'date': 'Wed Apr 27 2022 18:34:20.939 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 51
    roteiro = Roteiro(cena, ele, rot)
  module <module> line 18
    ator.tit = ator.nome
AttributeError: 'list' object has no attribute 'tit'
'''},
{'date': 'Wed Apr 27 2022 18:35:45.65 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 51
    roteiro = Roteiro(cena, ele, rot)
  module <module> line 19
    elenco.pop(0).vai = self.segue
AttributeError: 'list' object has no attribute 'vai'
'''},
{'date': 'Wed Apr 27 2022 18:36:58.772 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 19
  elenco.pop(0)ator.vai = self.segue
                ^
SyntaxError: invalid syntax
'''},
{'date': 'Wed Apr 27 2022 18:53:39.107 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _spy.vitollino.main line 475
    return self.vai(ev)
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 56
    rot = [Fala(ato, nome, None) for ato, nom in nome_ator]
NameError: name 'nome' is not defined
'''},
{'date': 'Wed Apr 27 2022 18:56:10.818 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 56
    rot = [Fala(ato, nome, None) for ato, nom in nome_ato]
NameError: name 'nome' is not defined
'''},
{'date': 'Wed Apr 27 2022 19:01:07.715 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 64
    rot = [Fala(ato, nom, None) for ato, nom in nome_ator]
TypeError: __init__() takes 3 positional argument but more were given
'''},
{'date': 'Wed Apr 27 2022 19:03:57.63 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 64
    rot = [Fala(ato, nom, None) for ato, nom in nome_ator]
TypeError: __init__() takes 3 positional argument but more were given
'''},
{'date': 'Thu Apr 28 2022 10:51:05.536 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 21
  protagonista = elenco.pop(0).ator else roteiro[0].ator
                                     ^
SyntaxError: invalid syntax
'''},
{'date': 'Thu Apr 28 2022 11:10:07.951 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 47
    class Guerreiras:
  module <module> line 48
    def __init__(self,nomes=NOMES, yy=40, xx=20, dx=100):
NameError: name 'NOMES' is not defined
'''},
{'date': 'Thu Apr 28 2022 11:10:25.529 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 68
    Guerreiras()
  module <module> line 49
    self.elenco = [Elemento(IMGUR.format(ELENCO[conta+1]), y=yy, x=xx+dx*conta, cena=cena) for conta in range(5)]
NameError: free variable 'cena' referenced before assignment in enclosing scope
'''},
{'date': 'Thu Apr 28 2022 11:24:02.174 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 65
    Guerreiras()
  module <module> line 64
    roteiro = Roteiro(cena, rot, ele)
  module <module> line 21
    ator.elt.style.filter = "brightness(30%)"
AttributeError: 'Elenco' object has no attribute 'elt'
'''},
{'date': 'Thu Apr 28 2022 11:30:49.55 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 47
  [ato.elt.style.filter = "brightness(100%)" for ato in self.atores]
  ^
IndentationError: expected an indented block
'''},
{'date': 'Thu Apr 28 2022 11:30:57.577 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 47
  [ato.elt.style.filter = "brightness(100%)" for ato in self.atores]
                                              ^
SyntaxError: invalid syntax
'''},
{'date': 'Thu Apr 28 2022 11:42:11.627 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 73
    Guerreiras()
  module <module> line 71
    rot = [Fala(ato, nom, prox) for ato, nom, prox in nome_ator]
TypeError: __new__() missing 1 positional argument: prox
'''},
{'date': 'Thu Apr 28 2022 11:44:32.131 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 6
    Fala = namedtuple('Fala','ator fala age prox', defaults=(None,))
TypeError: namedtuple() got an unexpected keyword argument 'defaults'
'''},
{'date': 'Thu Apr 28 2022 11:46:21.482 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 6
    Fala = namedtuple('Fala','ator fala age prox', defaults=(None,)*4)
TypeError: namedtuple() got an unexpected keyword argument 'defaults'
'''},
{'date': 'Thu Apr 28 2022 12:04:12.25 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 16
  prox = zip(roteiro, roteiro[1:]+[None]
                                                  ^
SyntaxError: invalid syntax
'''},
{'date': 'Thu Apr 28 2022 12:04:20.993 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 75
    Guerreiras()
  module <module> line 74
    roteiro = Roteiro(cena, rot, ele)
  module <module> line 17
    roteiro = [Fala(a, f, g, p.prox) for [a, f, g,_], p in prox]
AttributeError: 'NoneType' object has no attribute 'prox'
'''},
{'date': 'Thu Apr 28 2022 12:23:01.68 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 31
  self.mini = Elemento(
                                                                                          ^
SyntaxError: invalid syntax
'''},
{'date': 'Tue May 03 2022 18:20:30.366 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 110
    Sorrisos()
  module <module> line 101
    self.elenco = [Elemento(IMGUR.format(ELENCO[conta+1]), y=yy, x=xx+dx*conta, cena=cena) for conta in [0, 5]]
IndexError: list index out of range
'''},
{'date': 'Tue May 03 2022 18:27:13.54 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 18
  self.foi = foi or lambda _*: None
                              ^
SyntaxError: invalid syntax
'''},
{'date': 'Tue May 03 2022 18:27:48.674 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 18
  self.foi = foi if foi else lambda _*: None
                                       ^
SyntaxError: invalid syntax
'''},
{'date': 'Wed May 04 2022 05:01:02.101 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 127
    Sorrisos()
  module <module> line 122
    roteiro = Roteiro(cena, rot, ele, self.foi)
  module <module> line 21
    roteiro = [Fala(a, f, g, p.ator if p else None) for [a, f, g,_], p in prox]
TypeError: 'Fala' object is not iterable
'''},
{'date': 'Wed May 04 2022 10:20:30.832 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 161
    Guerreiras()
  module <module> line 122
    roteiro = Roteiro(cena, rot, ele)
  module <module> line 21
    roteiro = [Fala(a, f, g if g else p.ator, x ) for [a, f, g, x], p in prox]
AttributeError: 'NoneType' object has no attribute 'ator'
'''},
{'date': 'Wed May 04 2022 10:39:00.932 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 164
    Guerreiras()
  module <module> line 124
    roteiro = Roteiro(cena, rot, ele)
  module <module> line 21
    roteiro = [Fala(a, f, g if g else p.ator, x ) for [a, f, g, x], p in prox]
AttributeError: 'NoneType' object has no attribute 'ator'
'''},
{'date': 'Wed May 04 2022 10:43:43.107 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 166
    Guerreiras()
  module <module> line 127
    roteiro = Roteiro(cena, rot, ele)
  module <module> line 21
    roteiro = [Fala(a, f, g if g else p.ator, x ) for [a, f, g, x], p in prox]
AttributeError: 'NoneType' object has no attribute 'ator'
'''},
{'date': 'Mon May 09 2022 11:35:37.417 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 170
    Sorrisos()
  module <module> line 148
    roteiro = Roteiro(cena, rot, ele, self.foi)
  module <module> line 22
    roteiro = [Fala(a, f, g if g else (p.ator if p else None), x, mini=dic_ator[a].mini) for [a, f, g, x], p in prox]
TypeError: __new__() got an unexpected keyword argument 'mini'
'''},
{'date': 'Mon May 09 2022 11:39:05.771 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 170
    Sorrisos()
  module <module> line 148
    roteiro = Roteiro(cena, rot, ele, self.foi)
  module <module> line 22
    roteiro = [Fala(a, f, g if g else (p.ator if p else None), x, mini=dic_ator[a]) for [a, f, g, x], p in prox]
TypeError: __new__() got an unexpected keyword argument 'mini'
'''},
{'date': 'Mon May 09 2022 14:04:14.598 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 170
    Sorrisos()
  module <module> line 148
    roteiro = Roteiro(cena, rot, ele, self.foi)
  module <module> line 22
    roteiro = [Fala(a, f, g if g else (p.ator if p else None), x, mini=dic_ator[a].mini) for [a, f, g, x], p in prox]
TypeError: __new__() got an unexpected keyword argument 'mini'
'''},
{'date': 'Mon May 09 2022 14:12:33.240 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 173
    Sorrisos()
  module <module> line 141
    ele = [Ator(ato,nom, 1, A.e),
NameError: name 'ato' is not defined
'''},