
{'date': 'Wed Apr 13 2022 15:55:07.356 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 4
  GOGHIntru2 = 
                ^
SyntaxError: invalid syntax
'''},
{'date': 'Wed Apr 13 2022 15:55:24.668 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module browser.aio line 1
  <!DOCTYPE html>
  ^
SyntaxError: invalid syntax
'''},
{'date': 'Mon Apr 18 2022 14:56:50.57 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 32
    Cubos(CENAS)
  module <module> line 28
    cubos = [Cubo(inx=inx, faces=faces) for inx in range(12)]
NameError: name 'faces' is not defined
'''},
{'date': 'Mon Apr 18 2022 15:01:20.794 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 32
    Cubos(CENAS)
  module <module> line 28
    cubos = [Cubo(inx=inx, faces=cenas) for inx in range(12)]
  module <module> line 25
    self.faces = [Face(inx=inx, face=face) for face in faces]
  module <module> line 18
    w, h = tw//nx, h//ny
UnboundLocalError: local variable 'h' referenced before assignment
'''},
{'date': 'Mon Apr 18 2022 15:09:40.590 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 39
    Cubos(CENAS)
  module <module> line 35
    [cube.roll(0) for cube in cubos]
  module <module> line 31
    [face.show() if inx == face_index else face.hide() for face_index, face in enumerate(faces)]
NameError: name 'faces' is not defined
'''},
{'date': 'Mon Apr 18 2022 15:27:22.554 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 36
  }
  ^
SyntaxError: invalid syntax
'''},
{'date': 'Mon Apr 18 2022 15:39:46.985 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 54
    Cubos(CENAS)
  module <module> line 50
    [cube.roll(randint(0,5)) for cube in cubos]
  module <module> line 45
    self.face = [face.show() if inx == face_index else face.hide()
AttributeError: 'list' object has no attribute 'indexof'
'''},
{'date': 'Mon Apr 18 2022 15:41:17.474 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 54
    Cubos(CENAS)
  module <module> line 50
    [cube.roll(randint(0,5)) for cube in cubos]
  module <module> line 45
    self.face = [face.show() if inx == face_index else face.hide()
AttributeError: 'list' object has no attribute 'indexf'
'''},
{'date': 'Mon Apr 18 2022 15:49:52.242 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 56
    Cubos(CENAS)
  module <module> line 51
    cubos = [Cubo(inx=inx, faces=cenas) for inx in range(12)]
  module <module> line 45
    self.faces = [Face(cubo=self, inx=inx, face=face) for face in faces]
  module <module> line 22
    self.h = h
  module _spy.vitollino.main line 708
    self.elt.style.height = "{}px".format(value)
AttributeError: 'Face' object has no attribute 'elt'
'''},
{'date': 'Mon Apr 18 2022 15:51:18.964 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 56
    Cubos(CENAS)
  module <module> line 51
    cubos = [Cubo(inx=inx, faces=cenas) for inx in range(12)]
  module <module> line 45
    self.faces = [Face(cubo=self, inx=inx, face=face) for face in faces]
  module <module> line 22
    self.h = h
  module _spy.vitollino.main line 708
    self.elt.style.height = "{}px".format(value)
AttributeError: 'Face' object has no attribute 'elt'
'''},